# Site wide configuration

title: Waranga News
description: Serving the Waranga community for over 30 years
logo: wnews.png # 120x120 px default image used for Twitter summary card
banner: logo.png
#teaser: logo.png # 400x250 px default teaser image used in image archive grid
locale:
#url: http://www.wnews.org.au
url: //wnews.github.io
#url: http://localhost:63342/wnews.github.io/_site

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Ben Fortuna
  email: fortuna@micronode.com
  twitter: elbento
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: waranganews


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
